--------------------------------------------------------
--  File creato - giovedì-ottobre-29-2015   
--------------------------------------------------------
DROP TABLE "SCOTT"."ASSOCIAZIONE" cascade constraints;
DROP TABLE "SCOTT"."CATEGORIA_PIETANZA" cascade constraints;
DROP TABLE "SCOTT"."CATEGORIA_RISTORANTE" cascade constraints;
DROP TABLE "SCOTT"."CLIENTE" cascade constraints;
DROP TABLE "SCOTT"."ORDINE" cascade constraints;
DROP TABLE "SCOTT"."PIETANZA" cascade constraints;
DROP TABLE "SCOTT"."PREPARAZIONE" cascade constraints;
DROP TABLE "SCOTT"."RISTORANTE" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PIETANZA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."PIETANZA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RISTORANTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."RISTORANTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ASSOCIAZIONE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ASSOCIAZIONE" 
   (	"ID_ORDINE" NUMBER, 
	"ID_PIETANZA" NUMBER, 
	"QUANTITA" NUMBER DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA_PIETANZA
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CATEGORIA_PIETANZA" 
   (	"NOME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA_RISTORANTE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CATEGORIA_RISTORANTE" 
   (	"NOME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CLIENTE" 
   (	"ID" NUMBER, 
	"EMAIL" VARCHAR2(256 BYTE), 
	"PASSWORD" VARCHAR2(64 BYTE), 
	"NOME" VARCHAR2(20 BYTE), 
	"COGNOME" VARCHAR2(20 BYTE), 
	"INDIRIZZO" VARCHAR2(100 BYTE), 
	"CITTA" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDINE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ORDINE" 
   (	"ID" NUMBER, 
	"ID_CLIENTE" NUMBER, 
	"ID_RISTORANTE" NUMBER, 
	"DATA" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"IMPORTO" NUMBER(9,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PIETANZA
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PIETANZA" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(50 BYTE), 
	"CATEGORIA" VARCHAR2(20 BYTE), 
	"DESCRIZIONE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREPARAZIONE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PREPARAZIONE" 
   (	"ID_PIETANZA" NUMBER, 
	"ID_RISTORANTE" NUMBER, 
	"PREZZO" NUMBER(9,2), 
	"NOTE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RISTORANTE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."RISTORANTE" 
   (	"ID" NUMBER, 
	"EMAIL" VARCHAR2(256 BYTE), 
	"PASSWORD" VARCHAR2(64 BYTE), 
	"NOME" VARCHAR2(100 BYTE), 
	"CATEGORIA" VARCHAR2(30 BYTE), 
	"INDIRIZZO" VARCHAR2(100 BYTE), 
	"CITTA" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"DESCRIZIONE" VARCHAR2(100 BYTE), 
	"ORARIO_APERTURA" VARCHAR2(10 BYTE), 
	"ORARIO_CHIUSURA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.ASSOCIAZIONE
SET DEFINE OFF;
REM INSERTING into SCOTT.CATEGORIA_PIETANZA
SET DEFINE OFF;
REM INSERTING into SCOTT.CATEGORIA_RISTORANTE
SET DEFINE OFF;
REM INSERTING into SCOTT.CLIENTE
SET DEFINE OFF;
REM INSERTING into SCOTT.ORDINE
SET DEFINE OFF;
REM INSERTING into SCOTT.PIETANZA
SET DEFINE OFF;
REM INSERTING into SCOTT.PREPARAZIONE
SET DEFINE OFF;
REM INSERTING into SCOTT.RISTORANTE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ASSOCIAZIONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ASSOCIAZIONE_PK" ON "SCOTT"."ASSOCIAZIONE" ("ID_ORDINE", "ID_PIETANZA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATEGORIA_PIETANZA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."CATEGORIA_PIETANZA_PK" ON "SCOTT"."CATEGORIA_PIETANZA" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATEGORIA_RISTORANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."CATEGORIA_RISTORANTE_PK" ON "SCOTT"."CATEGORIA_RISTORANTE" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."CLIENTE_PK" ON "SCOTT"."CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_EMAIL_UX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."CLIENTE_EMAIL_UX" ON "SCOTT"."CLIENTE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ORDINE_PK" ON "SCOTT"."ORDINE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PIETANZA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PIETANZA_PK" ON "SCOTT"."PIETANZA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PIETANZA_NOME_UX
--------------------------------------------------------

  CREATE INDEX "SCOTT"."PIETANZA_NOME_UX" ON "SCOTT"."PIETANZA" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREPARAZIONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PREPARAZIONE_PK" ON "SCOTT"."PREPARAZIONE" ("ID_PIETANZA", "ID_RISTORANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RISTORANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."RISTORANTE_PK" ON "SCOTT"."RISTORANTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RISTORANTE_EMAIL_UX
--------------------------------------------------------

  CREATE INDEX "SCOTT"."RISTORANTE_EMAIL_UX" ON "SCOTT"."RISTORANTE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ASSOCIAZIONE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ASSOCIAZIONE" ADD CONSTRAINT "ASSOCIAZIONE_PK" PRIMARY KEY ("ID_ORDINE", "ID_PIETANZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."ASSOCIAZIONE" MODIFY ("ID_ORDINE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ASSOCIAZIONE" MODIFY ("ID_PIETANZA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ASSOCIAZIONE" MODIFY ("QUANTITA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA_PIETANZA
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CATEGORIA_PIETANZA" ADD CONSTRAINT "CATEGORIA_PIETANZA_PK" PRIMARY KEY ("NOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."CATEGORIA_PIETANZA" MODIFY ("NOME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA_RISTORANTE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CATEGORIA_RISTORANTE" ADD CONSTRAINT "CATEGORIA_RISTORANTE_PK" PRIMARY KEY ("NOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."CATEGORIA_RISTORANTE" MODIFY ("NOME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTE" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTE" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTE" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTE" MODIFY ("COGNOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTE" MODIFY ("INDIRIZZO" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTE" MODIFY ("CITTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDINE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ORDINE" ADD CONSTRAINT "ORDINE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."ORDINE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINE" MODIFY ("ID_RISTORANTE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINE" MODIFY ("DATA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINE" MODIFY ("IMPORTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PIETANZA
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PIETANZA" ADD CONSTRAINT "PIETANZA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."PIETANZA" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PIETANZA" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PIETANZA" MODIFY ("CATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREPARAZIONE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PREPARAZIONE" ADD CONSTRAINT "PREPARAZIONE_PK" PRIMARY KEY ("ID_PIETANZA", "ID_RISTORANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."PREPARAZIONE" MODIFY ("ID_PIETANZA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PREPARAZIONE" MODIFY ("ID_RISTORANTE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PREPARAZIONE" MODIFY ("PREZZO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RISTORANTE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."RISTORANTE" ADD CONSTRAINT "RISTORANTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("CATEGORIA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("INDIRIZZO" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("CITTA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("ORARIO_APERTURA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."RISTORANTE" MODIFY ("ORARIO_CHIUSURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ASSOCIAZIONE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ASSOCIAZIONE" ADD CONSTRAINT "ASSOCIAZIONE_FK1" FOREIGN KEY ("ID_ORDINE")
	  REFERENCES "SCOTT"."ORDINE" ("ID") ENABLE;
 
  ALTER TABLE "SCOTT"."ASSOCIAZIONE" ADD CONSTRAINT "ASSOCIAZIONE_FK2" FOREIGN KEY ("ID_PIETANZA")
	  REFERENCES "SCOTT"."PIETANZA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDINE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ORDINE" ADD CONSTRAINT "ORDINE_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "SCOTT"."CLIENTE" ("ID") ENABLE;
 
  ALTER TABLE "SCOTT"."ORDINE" ADD CONSTRAINT "ORDINE_FK2" FOREIGN KEY ("ID_RISTORANTE")
	  REFERENCES "SCOTT"."RISTORANTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PIETANZA
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PIETANZA" ADD CONSTRAINT "PIETANZA_FK1" FOREIGN KEY ("CATEGORIA")
	  REFERENCES "SCOTT"."CATEGORIA_PIETANZA" ("NOME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREPARAZIONE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PREPARAZIONE" ADD CONSTRAINT "PREPARAZIONE_FK1" FOREIGN KEY ("ID_PIETANZA")
	  REFERENCES "SCOTT"."PIETANZA" ("ID") ENABLE;
 
  ALTER TABLE "SCOTT"."PREPARAZIONE" ADD CONSTRAINT "PREPARAZIONE_FK2" FOREIGN KEY ("ID_RISTORANTE")
	  REFERENCES "SCOTT"."RISTORANTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RISTORANTE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."RISTORANTE" ADD CONSTRAINT "RISTORANTE_FK1" FOREIGN KEY ("CATEGORIA")
	  REFERENCES "SCOTT"."CATEGORIA_RISTORANTE" ("NOME") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."CLIENTE_TRG" 
BEFORE INSERT ON CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CLIENTE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PIETANZA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PIETANZA_TRG" 
BEFORE INSERT ON PIETANZA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PIETANZA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."PIETANZA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RISTORANTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."RISTORANTE_TRG" 
BEFORE INSERT ON RISTORANTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RISTORANTE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."RISTORANTE_TRG" ENABLE;
