--------------------------------------------------------
--  File creato - mercoledì-ottobre-28-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AMMINISTRATORI
--------------------------------------------------------

  CREATE TABLE "SCOTT"."AMMINISTRATORI" 
   (	"EMAIL" VARCHAR2(45 BYTE), 
	"PASSWORD" VARCHAR2(45 BYTE), 
	"NOME" VARCHAR2(25 BYTE), 
	"COGNOME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CATEGORIE" 
   (	"ID" NUMBER(11,0), 
	"DESCRIZIONE" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTI
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CLIENTI" 
   (	"NOME" VARCHAR2(25 BYTE), 
	"COGNOME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"INDIRIZZO" VARCHAR2(55 BYTE) DEFAULT '"Non specificato"', 
	"CAP" VARCHAR2(5 BYTE) DEFAULT NULL, 
	"PASSWORD" VARCHAR2(45 BYTE), 
	"PROVINCIA" VARCHAR2(2 BYTE) DEFAULT NULL, 
	"COMUNE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"RECAPITO" VARCHAR2(15 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESERCENTI
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ESERCENTI" 
   (	"ID" NUMBER(11,0), 
	"NOME" VARCHAR2(25 BYTE), 
	"COGNOME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"PASSWORD" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESERCENTI_FATTURATO
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ESERCENTI_FATTURATO" 
   (	"ID" NUMBER(11,0), 
	"NOME" VARCHAR2(25 BYTE), 
	"COGNOME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"PASSWORD" VARCHAR2(45 BYTE), 
	"TOTFATTURATO" NUMBER(28,2), 
	"NUMEVASI" NUMBER(21,0), 
	"NUMNEVASI" NUMBER(21,0), 
	"RICAVOADMIN" NUMBER(31,4)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESERCENTI_ORDINI_NON_EVASI
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ESERCENTI_ORDINI_NON_EVASI" 
   (	"ID_NEV" NUMBER(11,0), 
	"ORDINI_NON_EVASI" NUMBER(21,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESERCENTI_ORDINI_EVASI
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ESERCENTI_ORDINI_EVASI" 
   (	"ID_EV" NUMBER(11,0), 
	"TOTALE_FATTURATO" NUMBER(28,2), 
	"ORDINI_EVASI" NUMBER(21,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MENU" 
   (	"ID" NUMBER(11,0), 
	"ID_PUNTO_VENDITA" NUMBER(11,0), 
	"SOTTOCATEGORIA" VARCHAR2(45 BYTE), 
	"DETTAGLIO" VARCHAR2(400 BYTE), 
	"PREZZO" NUMBER(5,2), 
	"NOME" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDINAZIONI
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ORDINAZIONI" 
   (	"ID" NUMBER(11,0), 
	"EMAIL_CLIENTE" VARCHAR2(45 BYTE), 
	"ID_PUNTO_VENDITA" NUMBER(11,0), 
	"EVASO" NUMBER(1,0) DEFAULT 0, 
	"COSTO_TOTALE" NUMBER(6,2), 
	"INDIRIZZO_CONSEGNA" VARCHAR2(55 BYTE), 
	"CAP" VARCHAR2(5 BYTE), 
	"DATA_ORA_ORDINE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"DETTAGLI" VARCHAR2(1000 BYTE), 
	"NOTE_CONSEGNA" VARCHAR2(700 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PUNTI_VENDITA
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PUNTI_VENDITA" 
   (	"ID" NUMBER(11,0), 
	"ID_ESERCENTE" NUMBER(11,0), 
	"INDIRIZZO" VARCHAR2(55 BYTE), 
	"CAP" VARCHAR2(5 BYTE), 
	"LOGO" VARCHAR2(100 BYTE), 
	"COSTO_MINIMO_ORDINE" NUMBER(6,2) DEFAULT 0.00, 
	"COSTO_CONSEGNA" NUMBER(6,2) DEFAULT 0.00, 
	"TELEFONO" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"NOME_LOCALE" VARCHAR2(55 BYTE), 
	"PROVINCIA" VARCHAR2(2 BYTE) DEFAULT NULL, 
	"COMUNE" VARCHAR2(45 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.AMMINISTRATORI
SET DEFINE OFF;
REM INSERTING into SCOTT.CATEGORIE
SET DEFINE OFF;
REM INSERTING into SCOTT.CLIENTI
SET DEFINE OFF;
REM INSERTING into SCOTT.ESERCENTI
SET DEFINE OFF;
REM INSERTING into SCOTT.ESERCENTI_FATTURATO
SET DEFINE OFF;
REM INSERTING into SCOTT.ESERCENTI_ORDINI_NON_EVASI
SET DEFINE OFF;
REM INSERTING into SCOTT.ESERCENTI_ORDINI_EVASI
SET DEFINE OFF;
REM INSERTING into SCOTT.MENU
SET DEFINE OFF;
REM INSERTING into SCOTT.ORDINAZIONI
SET DEFINE OFF;
REM INSERTING into SCOTT.PUNTI_VENDITA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C0011248
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011248" ON "SCOTT"."AMMINISTRATORI" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011251
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011251" ON "SCOTT"."CATEGORIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011256
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011256" ON "SCOTT"."CLIENTI" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011262
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011262" ON "SCOTT"."ESERCENTI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011263
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011263" ON "SCOTT"."ESERCENTI" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011298
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011298" ON "SCOTT"."MENU" ("ID", "ID_PUNTO_VENDITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011290
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011290" ON "SCOTT"."ORDINAZIONI" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011279
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011279" ON "SCOTT"."PUNTI_VENDITA" ("ID", "ID_ESERCENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011280
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011280" ON "SCOTT"."PUNTI_VENDITA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AMMINISTRATORI
--------------------------------------------------------

  ALTER TABLE "SCOTT"."AMMINISTRATORI" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."AMMINISTRATORI" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."AMMINISTRATORI" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."AMMINISTRATORI" MODIFY ("COGNOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."AMMINISTRATORI" ADD PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CATEGORIE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CATEGORIE" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CATEGORIE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTI
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CLIENTI" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTI" MODIFY ("COGNOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTI" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTI" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CLIENTI" ADD PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESERCENTI
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ESERCENTI" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI" MODIFY ("COGNOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."ESERCENTI" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESERCENTI_FATTURATO
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ESERCENTI_FATTURATO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI_FATTURATO" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI_FATTURATO" MODIFY ("COGNOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI_FATTURATO" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI_FATTURATO" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESERCENTI_ORDINI_NON_EVASI
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ESERCENTI_ORDINI_NON_EVASI" MODIFY ("ID_NEV" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI_ORDINI_NON_EVASI" MODIFY ("ORDINI_NON_EVASI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESERCENTI_ORDINI_EVASI
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ESERCENTI_ORDINI_EVASI" MODIFY ("ID_EV" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ESERCENTI_ORDINI_EVASI" MODIFY ("ORDINI_EVASI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MENU" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."MENU" MODIFY ("ID_PUNTO_VENDITA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."MENU" MODIFY ("SOTTOCATEGORIA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."MENU" MODIFY ("PREZZO" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."MENU" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."MENU" ADD PRIMARY KEY ("ID", "ID_PUNTO_VENDITA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDINAZIONI
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ORDINAZIONI" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" MODIFY ("EMAIL_CLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" MODIFY ("ID_PUNTO_VENDITA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" MODIFY ("EVASO" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" MODIFY ("COSTO_TOTALE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" MODIFY ("INDIRIZZO_CONSEGNA" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" MODIFY ("CAP" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" MODIFY ("DATA_ORA_ORDINE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PUNTI_VENDITA
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PUNTI_VENDITA" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PUNTI_VENDITA" MODIFY ("ID_ESERCENTE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PUNTI_VENDITA" MODIFY ("INDIRIZZO" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PUNTI_VENDITA" MODIFY ("CAP" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PUNTI_VENDITA" MODIFY ("LOGO" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PUNTI_VENDITA" MODIFY ("NOME_LOCALE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PUNTI_VENDITA" ADD PRIMARY KEY ("ID", "ID_ESERCENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."PUNTI_VENDITA" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MENU" ADD FOREIGN KEY ("ID_PUNTO_VENDITA")
	  REFERENCES "SCOTT"."PUNTI_VENDITA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDINAZIONI
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ORDINAZIONI" ADD FOREIGN KEY ("EMAIL_CLIENTE")
	  REFERENCES "SCOTT"."CLIENTI" ("EMAIL") ENABLE;
 
  ALTER TABLE "SCOTT"."ORDINAZIONI" ADD FOREIGN KEY ("ID_PUNTO_VENDITA")
	  REFERENCES "SCOTT"."PUNTI_VENDITA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PUNTI_VENDITA
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PUNTI_VENDITA" ADD FOREIGN KEY ("ID_ESERCENTE")
	  REFERENCES "SCOTT"."ESERCENTI" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORIE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."CATEGORIE_TRG" 
BEFORE INSERT ON CATEGORIE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CATEGORIE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."CATEGORIE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESERCENTI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."ESERCENTI_TRG" 
BEFORE INSERT ON ESERCENTI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ESERCENTI_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."ESERCENTI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."MENU_TRG" 
BEFORE INSERT ON MENU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MENU_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."MENU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDINAZIONI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."ORDINAZIONI_TRG" 
BEFORE INSERT ON ORDINAZIONI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ORDINAZIONI_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."ORDINAZIONI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DATA_ORA_ORDINE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."DATA_ORA_ORDINE_TRG" 
BEFORE UPDATE ON ORDINAZIONI 
FOR EACH ROW 
BEGIN
  SELECT sysdate INTO :NEW.data_ora_ordine FROM DUAL;
END;
/
ALTER TRIGGER "SCOTT"."DATA_ORA_ORDINE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PUNTI_VENDITA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PUNTI_VENDITA_TRG" 
BEFORE INSERT ON PUNTI_VENDITA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PUNTI_VENDITA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."PUNTI_VENDITA_TRG" ENABLE;
